name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Coverage
      run: ./gradlew test jacocoTestReport

    - name: Upload Report
      uses: 'actions/upload-artifact@v2'
      with:
        name: report.xml
        path: ./build/jacoco/test/jacocoTestReport.xml

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.4
      with:
        paths: ./build/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 90
        min-coverage-changed-files: 90
        title: Code Coverage Report
        debug-mode: false

    - name: Generate JaCoCo badge
      id: jacocoBadge
      uses: cicirello/jacoco-badge-generator@v2
      with:
         jacoco-csv-file: ./build/jacoco/test/jacocoTestReport.csv
         badges-directory: .github/badges
         generate-branches-badge: false
         generate-summary: false
         colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
         intervals: 100 90 80 70 60 0
         on-missing-report: fail
         fail-if-coverage-less-than: 0
         fail-if-branches-less-than: 0
         fail-on-coverage-decrease: false
         fail-on-branches-decrease: false

    - name: Commit and push the coverage badges and summary file
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd .github/badges
        if [[ `git status --porcelain *.svg *.json` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.svg *.json
          git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
          git push
        fi