name: Coverage

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Test and Coverage
        run: ./gradlew test jacocoTestReport

      - name: Generate JaCoCo badge
        if: ${{ github.event_name != 'pull_request' }}
        id: jacocoBadge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ./build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          generate-branches-badge: false
          generate-summary: false
          colors: '#39C609 #a4a61d #EC2F0B'
          intervals: 100 80 0
          on-missing-report: fail
          fail-if-coverage-less-than: 0
          fail-if-branches-less-than: 0
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false

      - name: Checkout badges repository
        uses: actions/checkout@v3
        with:
          repository: cloudguy-it/repository-tools
          ref: main
          path: badges
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: doing commit badge repo
        run: |
          pwd
          ls -ltr
          git status

      - name: Commit and push the coverage badges and summary file
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd .github/badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badges" *.svg
            git push
          fi