name: Daily CI
on:
  push:
    branches: [ main ]

jobs:
  trivy_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Change Permission
        run: |
           chmod +x gradlew
           
      - name: Build with Gradle
        run: ./gradlewd quarkusBuilddd

      - name: Test with Gradle
        run: ./gradlew testdd

      
