name: detect-change-in-apis
on:
  push:
    branches: 
      - main
    paths:
      - 'src/main/resources/*'

jobs:
  check-yaml-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Save base branch app-configurations
        run: |
          yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > base_app_configs.yaml
          echo $(yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml)
          cat base_app_configs.yaml

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Save PR branch app-configurations
        run: |
          yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > pr_app_configs.yaml
          echo $(yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml)
          cat pr_app_configs.yaml

      - name: Compare app-configurations
        run: |
          if [ -f base_app_configs.yaml ] ; then
            echo "Base file found"
          else
            echo "Base file not found"
          fi
          if [ -f pr_app_configs.yaml ] ; then
            echo "PR file found"
          else
            echo "PR file not found"
          fi
          CHANGE_DETECTED=""
          for modules in $(yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N); do
            if ! diff <(yq e ".common-configurations.modules-configurations.${modules}" base_app_configs.yaml) <(yq e ".common-configurations.app-configurations.${modules}" pr_app_configs.yaml) > /dev/null; then
              CHANGE_DETECTED+="Change detected in ${modules} configurations. "
            fi
          done
          if [ -z "$CHANGE_DETECTED" ]; then
            echo "Change outside of modules-configurations"
          else
            echo $CHANGE_DETECTED
          fi
