name: Build and Analyze Project
on:
  pull_request:
    types:
      - opened

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '1.11'

      - name: Build Gradle Project
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_${{ runner.os }}_${{ env.TRIVY_VERSION }}.tar.gz
          tar zxvf trivy_${{ runner.os }}_${{ env.TRIVY_VERSION }}.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image with Trivy
        run: trivy image myapp:${{ github.sha }} --format json > trivy_report.json

      - name: Upload Trivy Report as Comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reportPath = './trivy_report.json';
            const report = fs.readFileSync(reportPath, 'utf8');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'COMMENT',
              body: '### Trivy Vulnerability Report\n\n' + report
            });
