name: Build and Analyze Project
on:
  pull_request:
    types:
      - opened

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install @actions/github
        run: npm install @actions/github

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Change Permission
        run: |
           chmod +x gradlew
           
      - name: Build with Gradle
        run: ./gradlew quarkusBuild
      
      - name: Build Docker Image
        run: docker build -f src/main/docker/Dockerfile.jvm -t myapp:${{ github.sha }} .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.42.1/trivy_0.42.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.42.1_Linux-64bit.tar.gz
          ls
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image with Trivy
        run: trivy image myapp:${{ github.sha }} --format json > trivy_report.json

      - name: Upload Trivy Report as Comment
        run: |
          report=$(cat trivy_report.json)
          echo "### Trivy Vulnerability Report\n\n$report" > comment.md
          echo "::set-output name=comment_path::comment.md" | tee -a comment-formated
        id: upload_comment
        
      - name: Read trivy report url
        id: trivy_report
        uses: juliangruber/read-file-action@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          path: comment-formated
          
      - name: trivy comment
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          header: "Trivy Vulnerability Report"
          message: |
            ## Trivy report
            ${{ steps.trivy_report.outputs.content }}
