name: Trivy analysis
on:
  pull_request:

jobs:
  trivy_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install @actions/github
        run: npm install @actions/github

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Change Permission
        run: |
           chmod +x gradlew
           
      - name: Build with Gradle
        run: ./gradlew quarkusBuild
      
      - name: Build Docker Image
        run: docker build -f src/main/docker/Dockerfile.jvm -t myapp:${{ github.sha }} .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.42.1/trivy_0.42.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.42.1_Linux-64bit.tar.gz
          ls
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{ github.sha }}'
          format: 'template'
          template: '@contrib/html.tpl'
          output: 'report.html'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Run Trivy vulnerability scanner
        id: trivyjson
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{ github.sha }}'
          format: 'json'
          output: 'report.json'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
      - name: Convert JSON to Markdown
        id: json-to-markdown
        uses: buildingcash/json-to-markdown-table-action@v1.0.0
        with:
          json: '${{ steps.trivyjson.outputs.report }}'
      - name: Save Markdown file
        run: echo "${{ steps.json-to-markdown.outputs.table }}" > report.md
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: report.md
          path: report.md
      - name: Comment on Pull Request with Report
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const artifactLink = `https://github.com/${owner}/${repo}/actions/artifacts/${{ github.run_id }}/artifacts_file/report.md`;
            const commentBody = `## Vulnerability Report\n\nThe vulnerability report is available [here](${artifactLink}).`;
            github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
      
