name: Detect Specific YAML Changes

on:
  push:
    branches:
      - main  # Adjust as necessary for your branch structure

jobs:
  yaml-change-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Necessary to get the previous commit for comparison

    - name: Install yq (YAML Processor)
      run: |
        sudo snap install yq

    - name: Analyze YAML changes according to rules
      run: |
        echo "Checking out the previous commit..."
        git checkout HEAD^ -- src/main/resources/api-gateway-updater.yaml
        echo "Extracting common-configurations section from the previous commit..."
        yq e '.common-configurations' src/main/resources/api-gateway-updater.yaml > prev_common_configs.yaml

        echo "Checking out the current commit..."
        git checkout HEAD -- src/main/resources/api-gateway-updater.yaml
        echo "Extracting common-configurations section from the current commit..."
        yq e '.common-configurations' src/main/resources/api-gateway-updater.yaml > current_common_configs.yaml

        echo "Comparing for changes in common-configurations outside modules-configurations..."
        if ! diff <(yq e 'del(.modules-configurations)' prev_common_configs.yaml) <(yq e 'del(.modules-configurations)' current_common_configs.yaml) > /dev/null; then
          echo "A change was performed in global modules. Modules available:"
          yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N
        else
          echo "No global changes detected. Checking for changes within each module in modules-configurations..."
          MODULES=$(yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N)
          for module in $MODULES; do
            echo "Checking changes in module: $module"
            if ! diff <(yq e ".common-configurations.modules-configurations.${module}" prev_common_configs.yaml) <(yq e ".common-configurations.modules-configurations.${module}" current_common_configs.yaml) > /dev/null; then
              echo "A change happens in module ${module}"
            fi
          done
        fi
