name: Check YAML Changes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch. Adjust as necessary.

jobs:
  check-yaml-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetches the last two commits for comparison

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Compare current and previous modules-configurations
      run: |
        # Extract modules-configurations from the last commit (previous state)
        git checkout HEAD^ -- src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > prev_modules_configs.yaml
        echo "Previous modules-configurations:"  # Debugging
        cat prev_modules_configs.yaml  # Debugging

        # Extract modules-configurations from the current commit (latest state)
        git checkout HEAD -- src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > current_modules_configs.yaml
        echo "Current modules-configurations:"  # Debugging
        cat current_modules_configs.yaml  # Debugging

        CHANGE_DETECTED=""
        MODULES=$(yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N)
        for module in $MODULES; do
          PREV_MODULE=$(yq e ".common-configurations.modules-configurations.${module}" prev_modules_configs.yaml)
          CURRENT_MODULE=$(yq e ".common-configurations.modules-configurations.${module}" current_modules_configs.yaml)
          if [ "$PREV_MODULE" != "$CURRENT_MODULE" ]; then
            CHANGE_DETECTED+="Change detected in ${module} configurations. "
          fi
        done
        if [ -z "$CHANGE_DETECTED" ]; then
          echo "Change outside of modules-configurations"
        else
          echo $CHANGE_DETECTED
        fi
