name: Detect Dynamic YAML Changes

on:
  push:
    branches:
      - main  # Adjust as necessary for your branch structure

jobs:
  dynamic-yaml-change-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Necessary to get the previous commit for comparison

    - name: Install yq (YAML Processor)
      run: |
        sudo snap install yq

    - name: Compare dynamic app configurations in YAML
      run: |
        # Checkout the previous commit for comparison
        git checkout HEAD^ -- src/main/resources/api-gateway-updater.yaml
        # Extract the list of applications from the previous state
        yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml > apps_list.txt
        # Save configurations for each app from the previous commit
        for app in $(cat apps_list.txt); do
          yq e ".common-configurations.modules-configurations.${app}" src/main/resources/api-gateway-updater.yaml > "prev_${app}_config.yaml"
        done

        # Checkout the current commit
        git checkout HEAD -- src/main/resources/api-gateway-updater.yaml
        # Save configurations for each app from the current commit
        for app in $(cat apps_list.txt); do
          yq e ".common-configurations.modules-configurations.${app}" src/main/resources/api-gateway-updater.yaml > "current_${app}_config.yaml"
        done

        # Detect changes
        CHANGE_DETECTED=""
        for app in $(cat apps_list.txt); do
          # Debug information
          echo "Comparing configurations for ${app}:"
          echo "Previous configuration:"
          cat "prev_${app}_config.yaml"
          echo "Current configuration:"
          cat "current_${app}_config.yaml"

          if ! diff "prev_${app}_config.yaml" "current_${app}_config.yaml" > /dev/null; then
            CHANGE_DETECTED+="Change detected in ${app} configurations. "
          fi
        done

        # Output results
        if [ -z "$CHANGE_DETECTED" ]; then
          echo "No changes detected in app configurations."
        else
          echo $CHANGE_DETECTED
        fi
