name: Check YAML Changes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch. Adjust as necessary.

jobs:
  check-yaml-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetches the last two commits for comparison

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Compare current and previous app1 and app2 configurations
      run: |
        # Extract app1 and app2 configurations from the last commit (previous state)
        git checkout HEAD^ -- src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations.app1' src/main/resources/api-gateway-updater.yaml > prev_app1_config.yaml
        yq e '.common-configurations.modules-configurations.app2' src/main/resources/api-gateway-updater.yaml > prev_app2_config.yaml
        echo "Previous app1 configuration:"  # Debugging
        cat prev_app1_config.yaml  # Debugging
        echo "Previous app2 configuration:"  # Debugging
        cat prev_app2_config.yaml  # Debugging

        # Extract app1 and app2 configurations from the current commit (latest state)
        git checkout HEAD -- src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations.app1' src/main/resources/api-gateway-updater.yaml > current_app1_config.yaml
        yq e '.common-configurations.modules-configurations.app2' src/main/resources/api-gateway-updater.yaml > current_app2_config.yaml
        echo "Current app1 configuration:"  # Debugging
        cat current_app1_config.yaml  # Debugging
        echo "Current app2 configuration:"  # Debugging
        cat current_app2_config.yaml  # Debugging

        CHANGE_DETECTED=""
        if ! diff prev_app1_config.yaml current_app1_config.yaml > /dev/null; then
          CHANGE_DETECTED+="Change detected in app1 configurations. "
        fi
        if ! diff prev_app2_config.yaml current_app2_config.yaml > /dev/null; then
          CHANGE_DETECTED+="Change detected in app2 configurations. "
        fi
        if [ -z "$CHANGE_DETECTED" ]; then
          echo "Change outside of app1 and app2 configurations"
        else
          echo $CHANGE_DETECTED
        fi
