name: Check YAML Changes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch. Adjust as necessary.

jobs:
  check-yaml-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetches the last two commits for comparison

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Compare current and previous app-configurations
      run: |
        # Extract app-configurations from the last commit (previous state)
        git checkout HEAD^ src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > prev_app_configs.yaml
        cat prev_app_configs.yaml

        # Extract app-configurations from the current commit (latest state)
        git checkout HEAD src/main/resources/api-gateway-updater.yaml
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > current_app_configs.yaml
        cat current_app_configs.yaml

        CHANGE_DETECTED=""
        for app in $(yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N); do
          if ! diff <(yq e ".common-configurations.modules-configurations.${app}" prev_app_configs.yaml) <(yq e ".common-configurations.modules-configurations.${app}" current_app_configs.yaml) > /dev/null; then
            CHANGE_DETECTED+="Change detected in ${app} configurations. "
          fi
        done
        if [ -z "$CHANGE_DETECTED" ]; then
          echo "Change outside of modules-configurations"
        else
          echo $CHANGE_DETECTED
        fi
