name: Detect YAML Changes with Specific Rules

on:
  push:
    branches:
      - main  # Adjust as necessary for your branch structure

jobs:
  yaml-change-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Necessary to get the previous commit for comparison

    - name: Install yq (YAML Processor)
      run: |
        sudo snap install yq

    - name: Analyze YAML changes
      run: |
        # Checkout the previous commit for comparison
        git checkout HEAD^ -- src/main/resources/api-gateway-updater.yaml
        # Save entire YAML file from the previous commit
        yq e '.' src/main/resources/api-gateway-updater.yaml > prev_full_yaml.yaml
        # Save modules-configurations section from the previous commit
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > prev_modules_configs.yaml

        # Checkout the current commit
        git checkout HEAD -- src/main/resources/api-gateway-updater.yaml
        # Save entire YAML file from the current commit
        yq e '.' src/main/resources/api-gateway-updater.yaml > current_full_yaml.yaml
        # Save modules-configurations section from the current commit
        yq e '.common-configurations.modules-configurations' src/main/resources/api-gateway-updater.yaml > current_modules_configs.yaml

        # Check for global changes outside modules-configurations
        if ! diff prev_modules_configs.yaml current_modules_configs.yaml > /dev/null; then
          echo "A change was performed in global modules. Modules available:"
          yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml
        else
          # Check for changes within each module in modules-configurations
          MODULES=$(yq e '.common-configurations.modules-configurations | keys' src/main/resources/api-gateway-updater.yaml -N)
          for module in $MODULES; do
            if ! diff <(yq e ".common-configurations.modules-configurations.${module}" prev_full_yaml.yaml) <(yq e ".common-configurations.modules-configurations.${module}" current_full_yaml.yaml) > /dev/null; then
              echo "A change happens in module ${module}"
            fi
          done
        fi
